name: "Deploy Static webapp Package"
on:
  workflow_call:
    inputs:
      artifact-name:
        description: "Nome do artefato"
        required: false
        type: string
        default: "build-${{ github.event.repository.name }}-${{ github.run_id }}"
      environment:
        description: "Ambiente"
        required: true
        type: string
      publish-profile:
        description: "Publish Profile"
        required: true
        type: string

    secrets: 
        publish-profile:
            description: "Publish Profile"
            required: true
    outputs:
      url:
        value: ${{ jobs.deploy-artifact.outputs.url }}
        description: "URL do Static Webapp App"

env:
  ARTIFACT_NAME: ${{ inputs.artifact-name }}
  PUBLISH_PROFILE_NAME: ${{inputs.publish-profile}}

jobs:
  deploy-artifact:
    name: "Static webapp Deploy"
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deployStaticWebapp.outputs.static_web_app_url }}
    environment: 
        name: ${{ inputs.environment }}
        url: ${{ steps.deployStaticWebapp.outputs.static_web_app_url }}
    steps:
      - name: "Download Artifact"
        uses: actions/download-artifact@v4
        with:
            name: ${{ env.ARTIFACT_NAME }}

      - name: "Unzip Artifact"
        shell: bash
        run: |
          unzip ${{env.ARTIFACT_NAME}}.zip -d .
          rm ${{env.ARTIFACT_NAME}}.zip

      - name: "Run process of Azure Functions Deploy"
        uses: Azure/static-web-apps-deploy@v1
        id: deployStaticWebapp
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          azure_static_web_apps_api_token: ${{ secrets.publish-profile }}
          action: "upload"
          app_location: "/"
          app_artifact_location: "/"
          skip_app_build: true